#apiVersion: v1
#kind: Pod
#metadata:
#  name: test
#spec:
#  containers:
#    - name: test
#      image: ubuntu
#      command:
#      - sleep
#      - "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: account
    bank: ivanoff
    env: prd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-account-db
  labels:
    app: account
    bank: ivanoff
    env: prd
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres
          command:
            - psql
            - "-c"
            - "CREATE DATABASE account;"
          env:
            - name: PGHOST
              value: rds-ivanoff-tf.c0whq4jiugzq.eu-north-1.rds.amazonaws.com
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ivanoff-db-creds
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: ivanoff-db-creds
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-nginx-config
data:
  nginx.conf: |-
    user nginx;
    worker_processes 4;
    
    events {
    	worker_connections 1024;
    }
    
    pid /var/run/nginx.pid;
    
    http {
    	default_type application/octet-stream;
    
    	log_format nginx_json escape=json '{'
    	'"http_host": "$http_host",'
    	'"remote_addr": "$remote_addr",'
    	'"status":"$status",'
    	'"body_bytes_sent":"$body_bytes_sent",'
    	'"http_user_agent":"$http_user_agent",'
    	'"request_method":"$request_method",'
    	'"request_time":"$request_time",'
    	'"upstream_response_time":"$upstream_response_time"'
    	'}';
    	
    	access_log /dev/stdout nginx_json;
        error_log /dev/stderr warn;
    	sendfile on;
    
    
    	server {
    		listen 80;

    		location / {
    			proxy_pass http://127.0.0.1:5000;
    		}
    		
    		location =/api/v1/account/health_check {
                        access_log off;
    			proxy_pass http://127.0.0.1:5000;
    		}
    	}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
    bank: ivanoff
    env: prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
      bank: ivanoff
      env: prd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: account
        bank: ivanoff
        env: prd
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.0
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
      - name: account
        image: gramal/dos14-account:571ab942282693e7839e0d4d2b4533eae1410115
        env:
        - name: PG_DATABASE
          value: account
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: ivanoff-db-creds
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ivanoff-db-creds
        - name: PG_HOST
          value: rds-ivanoff-tf.c0whq4jiugzq.eu-north-1.rds.amazonaws.com
        - name: PG_PORT
          value: "5432"
      volumes:
      - configMap:
          name: account-nginx-config
        name: nginx-config
