apiVersion: v1
kind: ConfigMap
metadata:
  name: account-nginx-config
data:
  nginx.conf: |-
    user nginx;
    worker_processes 4;
    
    events {
    	worker_connections 1024;
    }
    
    pid /var/run/nginx.pid;
    
    http {
    	default_type application/octet-stream;
    
    	log_format nginx_json escape=json '{'
    	'"http_host": "$http_host",'
    	'"remote_addr": "$remote_addr",'
    	'"status":"$status",'
    	'"body_bytes_sent":"$body_bytes_sent",'
    	'"http_user_agent":"$http_user_agent",'
    	'"request_method":"$request_method",'
    	'"request_time":"$request_time",'
    	'"upstream_response_time":"$upstream_response_time"'
    	'}';
    	
    	access_log /dev/stdout nginx_json;
        error_log /dev/stderr warn;
    	sendfile on;
    
    
    	server {
    		listen 80;

    		location / {
    			proxy_pass http://127.0.0.1:5000;
    		}
    		
    		location =/api/v1/account/health_check {
                        access_log off;
    			proxy_pass http://127.0.0.1:5000;
    		}
    	}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
    bank: ivanoff
    env: prd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account
      bank: ivanoff
      env: prd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: account
        bank: ivanoff
        env: prd
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.0
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
      - name: account
        image: gramal/dos14-account:571ab942282693e7839e0d4d2b4533eae1410115
        env:
        - name: PG_DATABASE
          value: postgres
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: ivanoff-db-creds
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ivanoff-db-creds
        - name: PG_HOST
          value: rds-ivanoff-tf.c0whq4jiugzq.eu-north-1.rds.amazonaws.com
        - name: PG_PORT
          value: "5432"
      volumes:
      - configMap:
          name: account-nginx-config
        name: nginx-config
